def text_repl(string_item):
    return (string_item.replace('PEAGE', 'PRTAGE').replace('PTERNHLY', 'PRERNHLY')
            .replace('PTERNWA', 'PRERNWA').replace('GEMETSTA', 'METSTA')
            .replace('GTMETSTA', 'METSTA').replace('PERACE', 'PRDTRACE')
            .replace('PTDTRACE', 'PRDTRACE').replace('PRORIGIN', 'PRDTHSP')
            .replace('HRHHID (partII)', 'HRHHID2').replace('PTERN2', 'PUERN2')
            .replace('PTIO1OCD', 'PEIO1OCD').replace('PUAFEVER', 'PEAFEVER')
            .replace('GECO', 'GTCO').replace('GEMSA', 'MSA').replace('GECMSA', 'CMSA')
            .replace('GTMSA', 'MSA').replace('GTCMSA', 'CMSA'))


VarList = ['PWORWGT', 'PWCMPWGT', 'PRERNWA',
           'PTERNWA', 'PWSSWGT', 'HRHHID (partII)', 
           'HRHHID2', 'HRYEAR', 'HRYEAR4', 'PRERNHLY',
           'PTERNHLY', 'HRMONTH', 'PESEX', 'PEMLR',
           'PENLFRET', 'PENLFACT', 'GESTFIPS',
           'HRMIS', 'PRFTLF', 'PEERNHRY', 'PWLGWGT',
           'PRSJMJ', 'PEEDUCA', 'PENATVTY', 'PUSLFPRX',
           'PRWKSTAT', 'PRMJOCC1', 'PRMJOCC2', 'PRMJIND1', 'PRMJIND2', 
           'GTMETSTA', 'GEMETSTA', 'GECO', 'GTCO', 'GEMSA', 'GECMSA',
           'PEDWWNTO', 'PRUNTYPE', 'GTCBSA', 'GTCMSA',
           'PERACE', 'PTDTRACE', 'PRDTRACE', 'PRORIGIN',
           'HUHHNUM', 'PRDTHSP', 'PRCHLD', 'PRTAGE',
           'PEAGE', 'PULINENO', 'PRWNTJOB', 'PEERNLAB',
           'PRUNEDUR', 'PEHRUSL1', 'PRMARSTA', 'PRCITSHP',
           'PRDTOCC1', 'PRDTOCC2', 'PRDTIND1', 'PRDTIND2', 
           'PEHRUSL2', 'PEHRUSLT', 'PEIO2COW',
           'PEIO1COW', 'PEIO1OCD', 'PEIO2OCD', 'PEIO1ICD', 'PEIO2ICD',
           'HRHHID', 'HRSAMPLE', 'HRSERSUF', 'PTIO1OCD',
           'PRDISFLG', 'PUAFEVER', 'PEAFEVER', 'PECERT1',
           'GTCSA', 'PEHRACTT', 'PEHRACT1', 'PEERNCOV',
           'PESCHENR', 'PRNMCHLD', 'PTERN2', 'PEHRACT2',
           'PUERN2', 'QSTNUM', 'OCCURNUM']

DataDict = {'January_2017_Record_Layout.txt':
            {'start': '2017-01-01', 'end': '2019-12-01',
             're': f'({"|".join(VarList)})\s+(\d+)\s+.*?\t+.*?(\d\d*).*?(\d\d+)'},
            'January_2015_Record_Layout.txt':
            {'start': '2015-01-01', 'end': '2016-12-31',
             're': f'({"|".join(VarList)})\s+(\d+)\s+.*?\t+.*?(\d\d*).*?(\d\d+)'},
            'January_2014_Record_Layout.txt':
            {'start': '2014-01-01', 'end': '2014-12-31',
             're': f'({"|".join(VarList)})\s+(\d+)\s+.*?\t+.*?(\d\d*).*?(\d\d+)'},
            'January_2013_Record_Layout.txt':
            {'start': '2013-01-01', 'end': '2013-12-31',
             're': f'({"|".join(VarList)})\s+(\d+)\s+.*?\t+.*?(\d\d*).*?(\d\d+)'},
            'may12dd.txt':
            {'start': '2012-05-01', 'end': '2012-12-31',
             're': f'({"|".join(VarList)})\s+(\d+)\s+.*?\t+.*?(\d\d*).*?(\d\d+)'},
            'jan10dd.txt':
            {'start': '2010-01-01', 'end': '2012-04-30',
             're': f'\n(?:\x0c)?({"|".join(VarList)})\s+(\d+)\s+.*? \s+.*?(\d\d*).*?(\d\d+)'},
            'jan09dd.txt':
            {'start': '2009-01-01', 'end': '2009-12-31',
             're': f'\n(?:\x0c)?({"|".join(VarList)})\s+(\d+)\s+.*? \s+.*?(\d\d*).*?(\d\d+)'},
            'jan07dd.txt':
            {'start': '2007-01-01', 'end': '2008-12-31',
             're': f'\n(?:\x0c)?({"|".join(VarList)})\s+(\d+)\s+.*? \s+.*?(\d\d*).*?(\d\d+)'},
            'augnov05dd.txt':
            {'start': '2005-08-01', 'end': '2006-12-31',
             're': f'\n(?:\x0c)?({"|".join(VarList)})\s+(\d+)\s+.*? \s+.*?(\d\d*).*?(\d\d+)'},
            'may04dd.txt':
            {'start': '2004-05-01', 'end': '2005-7-31',
             're': f'\n(?:\x0c)?({"|".join(VarList)})\s+(\d+)\s+.*? \s+.*?(\d\d*).*?(\d\d+)'},
            'jan03dd.txt':
            {'start': '2003-01-01', 'end': '2004-04-30',
             're': f'\n(?:\x0c)?({"|".join(VarList)})\s+(\d+)\s+.*? \s+.*?(\d\d*).*?(\d\d+)'},
            'jan98dd.asc':
            {'start': '1998-01-01', 'end': '1999-10-31',
             're': 'D (\w+)\s+(\d{1,2})\s+(\d+)\s+'},
            'jan98dd2.asc':
            {'start': '1999-11-01', 'end': '2002-12-31',
             're': 'D (\w+)\s+(\d{1,2})\s+(\d+)\s+'},
            'sep95_dec97_dd.txt':
            {'start': '1995-09-01', 'end': '1997-12-31',
             're': f'\n(?:\x0c)?({"|".join(VarList)})\s+(\d+)\s+.*? \s+.*?(\d\d*).*?(\d\d+)'},
            'jun95_aug95_dd.txt':
            {'start': '1995-06-01', 'end': '1995-08-31',
             're': f'\n(?:\x0c)?({"|".join(VarList)})\s+(\d+)\s+.*? \s+.*?(\d\d*).*?(\d\d+)'},
            'apr94_may95_dd.txt':
            {'start': '1994-04-01', 'end': '1995-05-31',
             're': f'\n(?:\x0c)?({"|".join(VarList)})\s+(\d+)\s+.*? \s+.*?(\d\d*).*?(\d\d+)'},
            'jan94_mar94_dd.txt':
            {'start': '1994-01-01', 'end': '1995-03-31',
             're': f'\n(?:\x0c)?({"|".join(VarList)})\s+(\d+)\s+.*? \s+.*?(\d\d*).*?(\d\d+)'},
#            'cps89.ddf':
#            {'start': '1989-01-01', 'end': '1991-12-31',
#             're': '(\w{1,2}[\$\-%]\w*|PADDING)\s*CHARACTER\*(\d{3})\s*\.{0,1}\s*\((\d*):(\d*)\).*'},
#            'cps92.ddf':
#            {'start': '1992-01-01', 'end': '1993-12-31',
#             're': '(\w{1,2}[\$\-%]\w*|PADDING)\s*CHARACTER\*(\d{3})\s*\.{0,1}\s*\((\d*):(\d*)\).*'}
            }
             
             
StatesMap = {1: 'AL',
             30: 'MT',
             2: 'AK',
             31: 'NE',
             4: 'AZ',
             32: 'NV',
             5: 'AR',
             33: 'NH',
             6: 'CA',
             34: 'NJ',
             8: 'CO',
             35: 'NM',
             9: 'CT',
             36: 'NY',
             10: 'DE',
             37: 'NC',
             11: 'DC',
             38: 'ND',
             12: 'FL',
             39: 'OH',
             13: 'GA',
             40: 'OK',
             15: 'HI',
             41: 'OR',
             16: 'ID',
             42: 'PA',
             17: 'IL',
             44: 'RI',
             18: 'IN',
             45: 'SC',
             19: 'IA',
             46: 'SD',
             20: 'KS',
             47: 'TN',
             21: 'KY',
             48: 'TX',
             22: 'LA',
             49: 'UT',
             23: 'ME',
             50: 'VT',
             24: 'MD',
             51: 'VA',
             25: 'MA',
             53: 'WA',
             26: 'MI',
             54: 'WV',
             27: 'MN',
             55: 'WI',
             28: 'MS',
             56: 'WY',
             29: 'MO'}

RegionsMap = {'AK': 'West',
              'HI': 'West',
              'WA': 'West',
              'OR': 'West',
              'CA': 'West',
              'NV': 'West',
              'ID': 'West',
              'MT': 'West',
              'UT': 'West',
              'AZ': 'West',
              'CO': 'West',
              'WY': 'West',
              'NM': 'West',
              'ND': 'Midwest',
              'SD': 'Midwest',
              'NE': 'Midwest',
              'KS': 'Midwest',
              'MN': 'Midwest',
              'IA': 'Midwest',
              'MO': 'Midwest',
              'WI': 'Midwest',
              'IL': 'Midwest',
              'IN': 'Midwest',
              'MI': 'Midwest',
              'OH': 'Midwest',
              'TX': 'South',
              'OK': 'South',
              'AR': 'South',
              'LA': 'South',
              'MS': 'South',
              'AL': 'South',
              'TN': 'South',
              'KY': 'South',
              'WV': 'South',
              'VA': 'South',
              'MD': 'South',
              'DE': 'South',
              'DC': 'South',
              'NC': 'South',
              'SC': 'South',
              'GA': 'South',
              'FL': 'South',
              'PA': 'Northeast',
              'NJ': 'Northeast',
              'NY': 'Northeast',
              'CT': 'Northeast',
              'RI': 'Northeast',
              'MA': 'Northeast',
              'NH': 'Northeast',
              'VT': 'Northeast',
              'ME': 'Northeast'}
          
COB1994Map = {57: 'United States',
              60: 'American Samoa',
              66: 'Guam',
              72: 'Puerto Rico',
              78: 'U.S. Virgin Islands',
              96: 'No coding available/US Outlying Area',
              102: 'Austria',
              103: 'Belgium',
              105: 'Czechoslovakia',
              106: 'Denmark',
              108: 'Finland',
              109: 'France',
              110: 'Germany',
              116: 'Greece',
              117: 'Hungary',
              119: 'Ireland/Eire',
              120: 'Italy',
              126: 'Holland/Netherlands',
              127: 'Norway',
              128: 'Poland',
              129: 'Portugal',
              130: 'Azores',
              132: 'Romania',
              134: 'Spain',
              136: 'Sweden',
              137: 'Switzerland',
              138: 'Great Britain',
              139: 'England',
              140: 'Scotland',
              142: 'Northern Ireland',
              147: 'Yugoslavia',
              148: 'Europe',
              155: 'Czech Republic',
              156: 'Slovakia/Slovak Republic',
              180: 'USSR',
              183: 'Latvia',
              184: 'Lithuania',
              185: 'Armenia',
              192: 'Russia',
              195: 'Ukraine',
              200: 'Afghanistan',
              202: 'Bangladesh',
              205: 'Burma',
              206: 'Cambodia',
              207: 'China',
              209: 'Hong Kong',
              210: 'India',
              211: 'Indonesia',
              212: 'Iran',
              213: 'Iraq',
              214: 'Israel',
              215: 'Japan',
              216: 'Jordan',
              217: 'Korea/South Korea',
              218: 'Korea/ South Korea',
              221: 'Laos',
              222: 'Lebanon',
              224: 'Malaysia',
              229: 'Pakistan',
              231: 'Philippines',
              233: 'Saudi Arabia',
              234: 'Singapore',
              237: 'Syria',
              238: 'Taiwan',
              239: 'Thailand',
              240: 'Turkey',
              242: 'Vietnam',
              245: 'Asia',
              252: 'Middle East',
              253: 'Palestine',
              300: 'Bermuda',
              301: 'Canada',
              304: 'North America',
              310: 'Belize',
              311: 'Costa Rica',
              312: 'El Salvador',
              313: 'Guatemala',
              314: 'Honduras',
              315: 'Mexico',
              316: 'Nicaragua',
              317: 'Panama',
              318: 'Central America',
              333: 'Bahamas',
              334: 'Barbados',
              337: 'Cuba',
              338: 'Dominica',
              339: 'Dominican Republic',
              340: 'Grenada',
              342: 'Haiti',
              343: 'Jamaica',
              351: 'Trinidad & Tobago',
              353: 'Caribbean',
              375: 'Argentina',
              376: 'Bolivia',
              377: 'Brazil',
              378: 'Chile',
              379: 'Colombia',
              380: 'Ecuador',
              383: 'Guyana',
              385: 'Peru',
              387: 'Uruguay',
              388: 'Venezuela',
              389: 'South America',
              415: 'Egypt',
              417: 'Ethiopia',
              421: 'Ghana',
              427: 'Kenya',
              436: 'Morocco',
              440: 'Nigeria',
              449: 'South Africa',
              462: 'Other Africa',
              468: 'North Africa',
              501: 'Australia',
              507: 'Fiji',
              514: 'New Zealand',
              527: 'Pacific Islands',
              555: 'Elsewhere'}
             
COB2007Map = {57: 'United States',
              60: 'American Samoa',
              66: 'Guam',
              69: 'Northern Marianas',
              73: 'Puerto Rico',
              78: 'U.S. Virgin Islands',
              96: 'Other US Island Areas',
              100: 'Albania',
              102: 'Austria',
              103: 'Belgium',
              104: 'Bulgaria',
              105: 'Czechoslovakia',
              106: 'Denmark',
              108: 'Finland',
              109: 'France',
              110: 'Germany',
              116: 'Greece',
              117: 'Hungary',
              118: 'Iceland',
              119: 'Ireland/Eire',
              120: 'Italy',
              126: 'Netherlands',
              127: 'Norway',
              128: 'Poland',
              129: 'Portugal',
              130: 'Azores',
              132: 'Romania',
              134: 'Spain',
              136: 'Sweden',
              137: 'Switzerland',
              138: 'United Kingdom',
              139: 'England',
              140: 'Scotland',
              141: 'Wales',
              142: 'Northern Ireland',
              147: 'Yugoslavia',
              148: 'Czech Republic',
              149: 'Slovakia',
              150: 'Bosnia & Herzegovina',
              151: 'Croatia',
              152: 'Macedonia',
              154: 'Serbia',
              155: 'Estonia',
              156: 'Latvia',
              157: 'Lithuania',
              158: 'Armenia',
              159: 'Azerbaijan',
              160: 'Belarus',
              161: 'Georgia',
              162: 'Moldova',
              163: 'Russia',
              164: 'Ukraine',
              165: 'USSR',
              166: 'Europe, n.s.',
              167: 'Kosovo',
              168: 'Montenegro',
              200: 'Afghanistan',
              202: 'Bangladesh',
              203: 'Bhutan',
              205: 'Myanmar (Burma)',
              206: 'Cambodia',
              207: 'China',
              208: 'Cyprus',
              209: 'Hong Kong',
              210: 'India',
              211: 'Indonesia',
              212: 'Iran',
              213: 'Iraq',
              214: 'Israel',
              215: 'Japan',
              216: 'Jordan',
              217: 'Korea',
              218: 'Kazakhstan',
              220: 'South Korea',
              222: 'Kuwait',
              223: 'Laos',
              224: 'Lebanon',
              226: 'Malaysia',
              228: 'Mongolia',
              229: 'Nepal',
              231: 'Pakistan',
              233: 'Philippines',
              235: 'Saudi Arabia',
              236: 'Singapore',
              238: 'Sri Lanka',
              239: 'Syria',
              240: 'Taiwan',
              242: 'Thailand',
              243: 'Turkey',
              245: 'United Arab Emirates',
              246: 'Uzbekistan',
              247: 'Vietnam',
              248: 'Yemen',
              249: 'Asia, n.s.',
              252: 'Middle East',
              300: 'Bermuda',
              301: 'Canada',
              303: 'Mexico',
              310: 'Belize',
              311: 'Costa Rica',
              312: 'El Salvador',
              313: 'Guatemala',
              314: 'Honduras',
              315: 'Nicaragua',
              316: 'Panama',
              321: 'Antigua and Barbuda',
              323: 'Bahamas',
              324: 'Barbados',
              327: 'Cuba',
              328: 'Dominica',
              329: 'Dominican Republic',
              330: 'Grenada',
              332: 'Haiti',
              333: 'Jamaica',
              338: 'St. Kitts--Nevis',
              339: 'St. Lucia',
              340: 'St. Vincent and the Grenadines',
              341: 'Trinidad & Tobago',
              343: 'West Indies, n.s.',
              360: 'Argentina',
              361: 'Bolivia',
              362: 'Brazil',
              363: 'Chile',
              364: 'Colombia',
              365: 'Ecuador',
              368: 'Guyana',
              369: 'Paraguay',
              370: 'Peru',
              372: 'Uruguay',
              373: 'Venezuela',
              374: 'South America, n.s.',
              399: 'Americas, n.s.',
              400: 'Algeria',
              407: 'Cameroon',
              408: 'Cape Verde',
              412: 'Congo',
              414: 'Egypt',
              416: 'Ethiopia',
              417: 'Eritrea',
              421: 'Ghana',
              423: 'Guinea',
              425: 'Ivory Coast',
              427: 'Kenya',
              429: 'Liberia',
              430: 'Libya',
              436: 'Morocco',
              440: 'Nigeria',
              444: 'Senegal',
              447: 'Sierra Leone',
              448: 'Somolia',
              449: 'South Africa',
              451: 'Sudan',
              453: 'Tanzania',
              454: 'Togo',
              457: 'Uganda',
              459: 'Zaire',
              460: 'Zambia',
              461: 'Zimbabwe',
              462: 'Africa, n.s.',
              501: 'Australia',
              508: 'Fiji',
              511: 'Marshall Islands',
              512: 'Micronesia',
              515: 'New Zealand',
              523: 'Tonga',
              527: 'Samoa',
              528: 'Oceania, n.s.',
              555: 'Elsewhere'}
              

CodebookNotes = {'MONTH': {'Notes': 'Survey reference month. Original CPS variable: HRMONTH', 
                           'Name': 'Month'},
                  'YEAR': {'Notes': 'Survey reference year. Original CPS variable: HRYEAR, HRYEAR4', 
                          'Name': 'Year'},
                  'MIS': {'Notes': 'Household month in sample. Original CPS variable: HRMIS',
                          'Name': 'Month in sample'},
                  'HHID': {'Notes': 'First part of CPS household ID. Original CPS variable HRHHID',
                          'Name': 'Household ID 1'},
                  'PULINENO': {'Notes': 'Unique line number for person.',
                          'Name': 'Person line number'},
                  'AGE': {'Notes': 'Person age, topcode varies by year, based on the original CPS data. Original CPS variable: PRTAGE, PEAGE',
                          'Name': 'Age'},
                  'HRSACTT': {'Notes': 'Actual hours worked in reference week, all jobs total.',
                          'Name': 'Actual hours worked, total'},        
                  'UNEMPDUR': {'Notes': 'Number of weeks person has been unemployed. There is a definition change in 1994 that affects the results from this variable. From 1994 onwards, those continuously employed and not in the incoming rotation group have their unemployment duration calculated based on the duration they reported in their incoming rotation group interview. Prior to 1994, respondents were asked how many weeks they were unemployed for all eligible months in sample.',
                          'Name': 'Unemployment Duration'},
                  'HRSUSL1': {'Notes': 'Usual hours worked at main job, per week.',
                          'Name': 'Usual hours worked, main job'},
                  'EDUC': {'Notes': 'Highest level of education attained: Advanced degree, college degree, some college but no degree or associate degree, high school degree, less than high school degree. Some assumptions are made to create this variable for pre-1992 data, using highest grade completed and highest graded attended, since the highest degree completed information is unavailable.',
                          'Name': 'Education level'},
                  'PTECON': {'Notes': 'Indicates person wants to work full-time but not able to for economic reasons. Derived from PRWKSTAT.',
                          'Name': 'Part-time for economic reasons'},
                  'COW1': {'Notes': 'Class of worker on main job. Derived from PEIO1COW.',
                          'Name': 'Class of worker 1'},
                  'COW2': {'Notes': 'Class of worker on second job. Derived from PEIO2COW.',
                           'Name': 'Class of worker 2'},
                  'LFS': {'Notes': 'Indicates whether someone is employed, unemployed, or not in the labor force (NILF).',
                          'Name': 'Labor force status'},
                  'EMP': {'Notes': 'Indicates if someone is employed, for any hours.',
                          'Name': 'Employed'},
                  'WBHAO': {'Notes': 'Time-consistent racial/ethnic group: white non-Hispanic, black non-Hispanic, Hispanic any race, Asian non-Hispanic, or other non-Hispanic (primarily native American).',
                          'Name': 'Race/Ethnic Group'},
                  'STATE': {'Notes': 'Two letter US state code. Derived from GESTFIPS.',
                          'Name': 'State'},
                  'REGION': {'Notes': 'Census regional grouping of states.',
                          'Name': 'Region'},
                  'FEMALE': {'Notes': 'Indicates if person is identified as female. Derived from PESEX.',
                          'Name': 'Female'},
                  'VETERAN': {'Notes': 'Indicates if person is a veteran. Derived from PEAFEVER.',
                              'Name': 'Veteran'},
                  'SCHENR': {'Notes': 'Indicates if person was enrolled in school during prior week. Derived from PESCHENR.',
                              'Name': 'School enrolled'},
                  'UNEMPTYPE': {'Notes': 'Type of unemployment: job loser/on layoff, job leaver, re-entrant, or new entrant.',
                              'Name': 'Unemployment type'},
                  'FORBORN': {'Notes': 'Indicates if person is born outside the US. Derived from PRCITSHP.',
                              'Name': 'Foreign born'},
                  'NILFREASON': {'Notes': 'Primary reason person is not in the labor force. Derived from PEMLR, PRWNTJOB, PEDWWNTO, and PENLFACT.',
                              'Name': 'NILF reason'},
                  'MINWAGE': {'Notes': 'Indicates if person is paid the federal minimum wage or less. Uses federal minimum wage data provided by the Department of Labor.',
                              'Name': 'Minimum wage'},
                  'CTYBIRTH': {'Notes': 'Country of birth. Slight change in values, starting in 2007.',
                              'Name': 'Birth country'},
                  'HHID2': {'Notes': 'Second piece of CPS unique household identifier. Created for months between January 1994 and May 2004, from HRSAMPLE, HRSERSUF, and HUHHNUM, otherwise derived from HRHHID2',
                              'Name': 'Household ID 2'},
                  'INDGRP': {'Notes': 'Major industry group', 'Name': 'Industry Group'},
                  'MARRIED': {'Notes': 'Indicates if person is currently married, with spouse present or spouse absent, but not separated. Derived from PRMARSTA.',
                          'Name': 'Married'},
                  'QSTNUM': {'Notes': 'Household number within current month. Created for months from January 1994 to December 1997.',
                              'Name': 'Unique household number'},
                  'OCCURNUM': {'Notes': 'Person number within household and current month. Created for months from January 1994 to December 2007.',
                              'Name': 'Unique person number'},
                  'CPSID': {'Notes': 'Manually created unique household ID that includes household start month and household number for start month. Can be used to match houeseholds over time. ',
                              'Name': 'Unique household ID'},
                  'PRCHLD': {'Notes': 'Age group of own children, following original CPS coding for variable of the same name.',
                              'Name': 'Own children ages'},
                  'PRNMCHLD': {'Notes': 'Number of own children.',
                              'Name': 'Number of own children'},
                  'WBHAOM': {'Notes': 'Racial/ethnic group with separate group for persons of more than one race.',
                              'Name': 'Race/ethnic group'},
                  'PRDTRACE': {'Notes': 'Original CPS definitions for race or combination of races', 'Name': 'Race/ethnicity'},
                  'HRSUSL2': {'Notes': 'Number of hours usually worked, per week, at second job', 'Name': 'Usual hours, job 2'},
                  'HRSUSLT': {'Notes': 'Number of hours usually worked, per week, total', 'Name': 'Usual hours, total'},
                  'HRSACT1': {'Notes': 'Number of hours actually worked last week, main job', 'Name': 'Actual hours, main job'},
                  'HRSACT2': {'Notes': 'Number of hours actually worked last week, second job', 'Name': 'Actual hours, job 2'},
                  'PEIO1ICD': {'Notes': 'Industry code for main job', 'Name': 'Industry, main job'},
                  'IND': {'Notes': 'Industry code for main job', 'Name': 'Industry, main job'},
                  'OCC': {'Notes': 'Occupation code for main job', 'Name': 'Occupation, main job'},
                  'PEIO1OCD': {'Notes': 'Occupation code for main job', 'Name': 'Occupation, main job'},
                  'PRDTIND1': {'Notes': 'Detailed industry recode, main job', 'Name': 'Industry, main job'},
                  'PRDTOCC1': {'Notes': 'Detailed occupation recode, main job', 'Name': 'Occupation, main job'},
                  'PRMJIND1': {'Notes': 'Major industry recode, main job', 'Name': 'Industry, main job'},
                  'PRMJOCC1': {'Notes': 'Major occupation recode, main job', 'Name': 'Occupation, main job'},
                  'IND': {'Notes': 'Industry code, main job. Includes 2000-2002 dual coded data provided by Census.', 'Name': 'Industry, main job'},
                  'IND2': {'Notes': 'Industry code, second job. Includes 2000-2002 dual coded data provided by Census.', 'Name': 'Industry, job 2'},
                  'INDD': {'Notes': 'Detailed industry recode, main job. Includes 2000-2002 dual coded data provided by Census.', 'Name': 'Detailed industry, main job'},
                  'IND2D': {'Notes': 'Detailed industry recode, second job. Includes 2000-2002 dual coded data provided by Census.', 'Name': 'Detailed industry, second job'},
                  'INDM': {'Notes': 'Major industry recode, main job. Includes 2000-2002 dual coded data provided by Census.', 'Name': 'Major industry, main job'},
                  'IND2M': {'Notes': 'Major industry recode, second job. Includes 2000-2002 dual coded data provided by Census.', 'Name': 'Major industry, second job'},
                  'OCC': {'Notes': 'Occupation code, main job. Includes 2000-2002 dual coded data provided by Census.', 'Name': 'Occupation, main job'},
                  'OCC2': {'Notes': 'Occupation code, second job. Includes 2000-2002 dual coded data provided by Census.', 'Name': 'Occupation, second job'},
                  'OCCD': {'Notes': 'Detailed occupation recode, main job. Includes 2000-2002 dual coded data provided by Census.', 'Name': 'Detailed occupation, main job'},
                  'OCC2D': {'Notes': 'Detailed occupation recode, second job. Includes 2000-2002 dual coded data provided by Census.', 'Name': 'Detailed occupation, job 2'},
                  'OCCM': {'Notes': 'Major occupation recode, main job. Includes 2000-2002 dual coded data provided by Census.', 'Name': 'Major occupation, main job'},
                  'OCC2M': {'Notes': 'Major occupation recode, second job. Includes 2000-2002 dual coded data provided by Census.', 'Name': 'Major occupation, job 2'},
                  'IND80': {'Notes': 'Industry code, main job, 1980 basis', 'Name': 'Industry, main job'},
                  'IND280': {'Notes': 'Industry code, second job, 1980 basis', 'Name': 'Industry, job 2'},
                  'IND80D': {'Notes': 'Detailed industry recode, main job, 1980 basis', 'Name': 'Detailed industry, main job'},
                  'IND280D': {'Notes': 'Detailed industry recode, second job, 1980 basis', 'Name': 'Detailed industry, second job'},
                  'IND80M': {'Notes': 'Major industry recode, main job, 1980 basis', 'Name': 'Major industry, main job'},
                  'IND280M': {'Notes': 'Major industry recode, second job, 1980 basis', 'Name': 'Major industry, second job'},
                  'OCC80': {'Notes': 'Occupation code, main job, 1980 basis', 'Name': 'Occupation, main job'},
                  'OCC280': {'Notes': 'Occupation code, second job, 1980 basis', 'Name': 'Occupation, second job'},
                  'OCC80D': {'Notes': 'Detailed occupation recode, main job, 1980 basis', 'Name': 'Detailed occupation, main job'},
                  'OCC280D': {'Notes': 'Detailed occupation recode, second job, 1980 basis', 'Name': 'Detailed occupation, job 2'},
                  'OCC80M': {'Notes': 'Major occupation recode, main job, 1980 basis', 'Name': 'Major occupation, main job'},
                  'OCC280M': {'Notes': 'Major occupation recode, second job, 1980 basis', 'Name': 'Major occupation, job 2'},
                  'PWLGWGT': {'Notes': 'Person weight for matching month to month CPS observations.', 'Name': 'Longitudinal person weight'},
                  'PWSSWGT': {'Notes': 'Person weight, including children.', 'Name': 'Person weight'},
                  'CBSA': {'Notes': 'Similar to metro area.',
                              'Name': 'Center-based statistical area'},
                  'CSA': {'Notes': 'Grouping of nearby metro areas.',
                              'Name': 'Consolidated statistical area'},
                  'COUNTY': {'Notes': 'U.S. county code, derived from GECO and GTCO', 'Name': 'County'},
                  'MSA': {'Notes': 'Metropolitan Statistical Area (MSA) code', 'Name': 'MSA code'},
                  'CMSA': {'Notes': 'Combined Metropolitan Statistical Area (MSA) code', 'Name': 'CMSA code'},
                  'DISABILITY': {'Notes': 'Indicates if person is has any of six disabilities: difficulty hearing, difficulty seeing even with glasses, difficulty remembering or making decisions, difficulty walking or climbing stairs, difficulty dressing or bathing, or difficulty doing errands alone. Includes data covering June to December 2008 that is released separately by Census. Derived from PRDISFLG.',
                              'Name': 'Disability'},
                  'CERT': {'Notes': 'Indicates if a person has a professional certification or license. Values for 2015 and 2016 added using separately published Census microdata. Derived from PECERT1.',
                              'Name': 'Professional certification'},
                  'WORKFT': {'Notes': 'Indicates if person worked full-time (35 hours or more) in the reference week. Derived from PRWKSTAT.',
                          'Name': 'Worked full-time'},
                  'UNION': {'Notes': 'Indicates if person is covered by a union contract or similar collective bargaining agreement. Uses revised data for 2001 and 2002, provided by Census. Derived from PEERNLAB and PEERNCOV.',
                          'Name': 'Union'},
                  'UNIONMEM': {'Notes': 'Indicates if person is a member of a union or similar employee association. Uses revised data for 2001 and 2002, provided by Census. Derived from PEERNLAB.',
                          'Name': 'Union member'},
                  'PAIDHRLY': {'Notes': 'Indicates whether person is usually paid on a per-hour basis. Derived from PEERNHRY.',
                          'Name': 'Paid hourly'},
                  'WKWAGE': {'Notes': 'Nominal weekly earnings, in USD.',
                          'Name': 'Weekly wage'},
                  'HRWAGE': {'Notes': 'Nominal hourly earnings, in USD. Includes hourly wage calculation for individuals who report their pay on a weekly basis and report their hours worked. Use in combination with PAIDHRLY to identify only people who are paid on an hourly basis.',
                          'Name': 'Hourly wage'},
                  'RWKWAGE': {'Notes': 'Real weekly earnings, in USD, adjusted for inflation by regional CPI-U.',
                          'Name': 'Real weekly wage'},
                  'RHRWAGE': {'Notes': 'Real hourly earnings, in USD, adjusted for inflation by regional CPI-U. Includes hourly wage calculation for individuals who report their pay on a weekly basis and report their hours worked. Use in combination with PAIDHRLY to identify only people who are paid on an hourly basis.',
                          'Name': 'Real hourly wage'},
                  'BASICWGT': {'Notes': 'Basic person weight, equal to the composite weight where available (1998-onward). Basic weight for 2000-2002 is revised based on Census released 2000-based weights and based on revised December 2007 weights from Census.',
                          'Name': 'Basic weight'},
                  'PWORWGT': {'Notes': 'Person weight for outgoing rotation group variables, such as wage or hours or union membership. ORG weight for 2000-2002 is revised based on Census released 2000-based weights.',
                          'Name': 'Female'},
                  'PROXY': {'Notes': 'Identifies whether labor force information was collected by self, by proxy response, or both. Derived from PUSLFPRX.', 'Name': 'Proxy response'},
                  'MJH': {'Notes': 'Indicates if person has more than one job. Derived from PRSJMJ.',
                          'Name': 'Multiple jobholder'}}
                        

ValueLabels = {'OCC': {10: 'Chief executives',
 20: 'General and operations managers',
 30: 'Legislators',
 40: 'Advertising and promotions managers',
 50: 'Marketing and sales managers',
 60: 'Public relations and fundraising managers',
 100: 'Administrative services managers',
 110: 'Computer and information systems managers',
 120: 'Financial managers',
 135: 'Compensation and benefits managers',
 136: 'Human resources managers',
 137: 'Training and development managers',
 140: 'Industrial production managers',
 150: 'Purchasing managers',
 160: 'Transportation, storage, and distribution managers',
 205: 'Farmers, ranchers, and other agricultural managers',
 220: 'Construction managers',
 230: 'Education administrators',
 300: 'Architectural and engineering managers',
 310: 'Food service managers',
 325: 'Funeral service managers',
 330: 'Gaming managers',
 340: 'Lodging managers',
 350: 'Medical and health services managers',
 360: 'Natural sciences managers',
 400: 'Postmasters and mail superintendents',
 410: 'Property, real estate, and community association managers',
 420: 'Social and community service managers',
 425: 'Emergency management directors',
 430: 'Managers, all other',
 500: 'Agents and business managers of artists, performers, and athletes',
 510: 'Buyers and purchasing agents, farm products',
 520: 'Wholesale and retail buyers, except farm products',
 530: 'Purchasing agents, except wholesale, retail, and farm products',
 540: 'Claims adjusters, appraisers, examiners, and investigators',
 565: 'Compliance officers',
 600: 'Cost estimators',
 630: 'Human resources workers',
 640: 'Compensation, benefits, and job analysis specialists',
 650: 'Training and development specialists',
 700: 'Logisticians',
 710: 'Management analysts',
 725: 'Meeting, convention, and event planners',
 726: 'Fundraisers',
 735: 'Market research analysts and marketing specialists',
 740: 'Business operations specialists, all other',
 800: 'Accountants and auditors',
 810: 'Appraisers and assessors of real estate',
 820: 'Budget analysts',
 830: 'Credit analysts',
 840: 'Financial analysts',
 850: 'Personal financial advisors',
 860: 'Insurance underwriters',
 900: 'Financial examiners',
 910: 'Credit counselors and loan officers',
 930: 'Tax examiners and collectors, and revenue agents',
 940: 'Tax preparers',
 950: 'Financial specialists, all other',
 1005: 'Computer and information research scientists',
 1006: 'Computer systems analysts',
 1007: 'Information security analysts',
 1010: 'Computer programmers',
 1020: 'Software developers, applications and systems software',
 1030: 'Web developers',
 1050: 'Computer support specialists',
 1060: 'Database administrators',
 1105: 'Network and computer systems administrators',
 1106: 'Computer network architects',
 1107: 'Computer occupations, all other',
 1200: 'Actuaries',
 1210: 'Mathematicians',
 1220: 'Operations research analysts',
 1230: 'Statisticians',
 1240: 'Miscellaneous mathematical science occupations',
 1300: 'Architects, except naval',
 1310: 'Surveyors, cartographers, and photogrammetrists',
 1320: 'Aerospace engineers',
 1330: 'Agricultural engineers',
 1340: 'Biomedical engineers',
 1350: 'Chemical engineers',
 1360: 'Civil engineers',
 1400: 'Computer hardware engineers',
 1410: 'Electrical and electronics engineers',
 1420: 'Environmental engineers',
 1430: 'Industrial engineers, including health and safety',
 1440: 'Marine engineers and naval architects',
 1450: 'Materials engineers',
 1460: 'Mechanical engineers',
 1500: 'Mining and geological engineers, including mining safety engineers',
 1510: 'Nuclear engineers',
 1520: 'Petroleum engineers',
 1530: 'Engineers, all other',
 1540: 'Drafters',
 1550: 'Engineering technicians, except drafters',
 1560: 'Surveying and mapping technicians',
 1600: 'Agricultural and food scientists',
 1610: 'Biological scientists',
 1640: 'Conservation scientists and foresters',
 1650: 'Medical scientists',
 1660: 'Life scientists, all other',
 1700: 'Astronomers and physicists',
 1710: 'Atmospheric and space scientists',
 1720: 'Chemists and materials scientists',
 1740: 'Environmental scientists and geoscientists',
 1760: 'Physical scientists, all other',
 1800: 'Economists',
 1815: 'Survey researchers',
 1820: 'Psychologists',
 1830: 'Sociologists',
 1840: 'Urban and regional planners',
 1860: 'Miscellaneous social scientists and related workers',
 1900: 'Agricultural and food science technicians',
 1910: 'Biological technicians',
 1920: 'Chemical technicians',
 1930: 'Geological and petroleum technicians',
 1940: 'Nuclear technicians',
 1950: 'Social science research assistants',
 1965: 'Miscellaneous life, physical, and social science technicians',
 2000: 'Counselors',
 2010: 'Social workers',
 2015: 'Probation officers and correctional treatment specialists',
 2016: 'Social and human service assistants',
 2025: 'Miscellaneous community and social service specialists, including health educators and community health workers',
 2040: 'Clergy',
 2050: 'Directors, religious activities and education',
 2060: 'Religious workers, all other',
 2100: 'Lawyers',
 2105: 'Judicial law clerks',
 2110: 'Judges, magistrates, and other judicial workers',
 2145: 'Paralegals and legal assistants',
 2160: 'Miscellaneous legal support workers',
 2200: 'Postsecondary teachers',
 2300: 'Preschool and kindergarten teachers',
 2310: 'Elementary and middle school teachers',
 2320: 'Secondary school teachers',
 2330: 'Special education teachers',
 2340: 'Other teachers and instructors',
 2400: 'Archivists, curators, and museum technicians',
 2430: 'Librarians',
 2440: 'Library technicians',
 2540: 'Teacher assistants',
 2550: 'Other education, training, and library workers',
 2600: 'Artists and related workers',
 2630: 'Designers',
 2700: 'Actors',
 2710: 'Producers and directors',
 2720: 'Athletes, coaches, umpires, and related workers',
 2740: 'Dancers and choreographers',
 2750: 'Musicians, singers, and related workers',
 2760: 'Entertainers and performers, sports and related workers, all other',
 2800: 'Announcers',
 2810: 'News analysts, reporters and correspondents',
 2825: 'Public relations specialists',
 2830: 'Editors',
 2840: 'Technical writers',
 2850: 'Writers and authors',
 2860: 'Miscellaneous media and communication workers',
 2900: 'Broadcast and sound engineering technicians and radio operators',
 2910: 'Photographers',
 2920: 'Television, video, and motion picture camera operators and editors',
 2960: 'Media and communication equipment workers, all other',
 3000: 'Chiropractors',
 3010: 'Dentists',
 3030: 'Dietitians and nutritionists',
 3040: 'Optometrists',
 3050: 'Pharmacists',
 3060: 'Physicians and surgeons',
 3110: 'Physician assistants',
 3120: 'Podiatrists',
 3140: 'Audiologists',
 3150: 'Occupational therapists',
 3160: 'Physical therapists',
 3200: 'Radiation therapists',
 3210: 'Recreational therapists',
 3220: 'Respiratory therapists',
 3230: 'Speech-language pathologists',
 3235: 'Exercise physiologists',
 3245: 'Therapists, all other',
 3250: 'Veterinarians',
 3255: 'Registered nurses',
 3256: 'Nurse anesthetists',
 3257: 'Nurse midwives',
 3258: 'Nurse practitioners',
 3260: 'Health diagnosing and treating practitioners, all other',
 3300: 'Clinical laboratory technologists and technicians',
 3310: 'Dental hygienists',
 3320: 'Diagnostic related technologists and technicians',
 3400: 'Emergency medical technicians and paramedics',
 3420: 'Health practitioner support technologists and technicians',
 3500: 'Licensed practical and licensed vocational nurses',
 3510: 'Medical records and health information technicians',
 3520: 'Opticians, dispensing',
 3535: 'Miscellaneous health technologists and technicians',
 3540: 'Other healthcare practitioners and technical occupations',
 3600: 'Nursing, psychiatric, and home health aides',
 3610: 'Occupational therapy assistants and aides',
 3620: 'Physical therapist assistants and aides',
 3630: 'Massage therapists',
 3640: 'Dental assistants',
 3645: 'Medical assistants',
 3646: 'Medical transcriptionists',
 3647: 'Pharmacy aides',
 3648: 'Veterinary assistants and laboratory animal caretakers',
 3649: 'Phlebotomists',
 3655: 'Miscellaneous healthcare support occupations, including medical equipment preparers',
 3700: 'First-line supervisors of correctional officers',
 3710: 'First-line supervisors of police and detectives',
 3720: 'First-line supervisors of fire fighting and prevention workers',
 3730: 'First-line supervisors of protective service workers, all other',
 3740: 'Firefighters',
 3750: 'Fire inspectors',
 3800: 'Bailiffs, correctional officers, and jailers',
 3820: 'Detectives and criminal investigators',
 3830: 'Fish and game wardens',
 3840: 'Parking enforcement workers',
 3850: "Police and sheriff's patrol officers",
 3860: 'Transit and railroad police',
 3900: 'Animal control workers',
 3910: 'Private detectives and investigators',
 3930: 'Security guards and gaming surveillance officers',
 3940: 'Crossing guards',
 3945: 'Transportation security screeners',
 3955: 'Lifeguards and other recreational, and all other protective service workers',
 4000: 'Chefs and head cooks',
 4010: 'First-line supervisors of food preparation and serving workers',
 4020: 'Cooks',
 4030: 'Food preparation workers',
 4040: 'Bartenders',
 4050: 'Combined food preparation and serving workers, including fast food',
 4060: 'Counter attendants, cafeteria, food concession, and coffee shop',
 4110: 'Waiters and waitresses',
 4120: 'Food servers, nonrestaurant',
 4130: 'Dining room and cafeteria attendants and bartender helpers',
 4140: 'Dishwashers',
 4150: 'Hosts and hostesses, restaurant, lounge, and coffee shop',
 4160: 'Food preparation and serving related workers, all other',
 4200: 'First-line supervisors of housekeeping and janitorial workers',
 4210: 'First-line supervisors of landscaping, lawn service, and groundskeeping workers',
 4220: 'Janitors and building cleaners',
 4230: 'Maids and housekeeping cleaners',
 4240: 'Pest control workers',
 4250: 'Grounds maintenance workers',
 4300: 'First-line supervisors of gaming workers',
 4320: 'First-line supervisors of personal service workers',
 4340: 'Animal trainers',
 4350: 'Nonfarm animal caretakers',
 4400: 'Gaming services workers',
 4410: 'Motion picture projectionists',
 4420: 'Ushers, lobby attendants, and ticket takers',
 4430: 'Miscellaneous entertainment attendants and related workers',
 4460: 'Embalmers and funeral attendants',
 4465: 'Morticians, undertakers, and funeral directors',
 4500: 'Barbers',
 4510: 'Hairdressers, hairstylists, and cosmetologists',
 4520: 'Miscellaneous personal appearance workers',
 4530: 'Baggage porters, bellhops, and concierges',
 4540: 'Tour and travel guides',
 4600: 'Childcare workers',
 4610: 'Personal care aides',
 4620: 'Recreation and fitness workers',
 4640: 'Residential advisors',
 4650: 'Personal care and service workers, all other',
 4700: 'First-line supervisors of retail sales workers',
 4710: 'First-line supervisors of non-retail sales workers',
 4720: 'Cashiers',
 4740: 'Counter and rental clerks',
 4750: 'Parts salespersons',
 4760: 'Retail salespersons',
 4800: 'Advertising sales agents',
 4810: 'Insurance sales agents',
 4820: 'Securities, commodities, and financial services sales agents',
 4830: 'Travel agents',
 4840: 'Sales representatives, services, all other',
 4850: 'Sales representatives, wholesale and manufacturing',
 4900: 'Models, demonstrators, and product promoters',
 4920: 'Real estate brokers and sales agents',
 4930: 'Sales engineers',
 4940: 'Telemarketers',
 4950: 'Door-to-door sales workers, news and street vendors, and related workers',
 4965: 'Sales and related workers, all other',
 5000: 'First-line supervisors of office and administrative support workers',
 5010: 'Switchboard operators, including answering service',
 5020: 'Telephone operators',
 5030: 'Communications equipment operators, all other',
 5100: 'Bill and account collectors',
 5110: 'Billing and posting clerks',
 5120: 'Bookkeeping, accounting, and auditing clerks',
 5130: 'Gaming cage workers',
 5140: 'Payroll and timekeeping clerks',
 5150: 'Procurement clerks',
 5160: 'Tellers',
 5165: 'Financial clerks, all other',
 5200: 'Brokerage clerks',
 5210: 'Correspondence clerks',
 5220: 'Court, municipal, and license clerks',
 5230: 'Credit authorizers, checkers, and clerks',
 5240: 'Customer service representatives',
 5250: 'Eligibility interviewers, government programs',
 5260: 'File clerks',
 5300: 'Hotel, motel, and resort desk clerks',
 5310: 'Interviewers, except eligibility and loan',
 5320: 'Library assistants, clerical',
 5330: 'Loan interviewers and clerks',
 5340: 'New accounts clerks',
 5350: 'Order clerks',
 5360: 'Human resources assistants, except payroll and timekeeping',
 5400: 'Receptionists and information clerks',
 5410: 'Reservation and transportation ticket agents and travel clerks',
 5420: 'Information and record clerks, all other',
 5500: 'Cargo and freight agents',
 5510: 'Couriers and messengers',
 5520: 'Dispatchers',
 5530: 'Meter readers, utilities',
 5540: 'Postal service clerks',
 5550: 'Postal service mail carriers',
 5560: 'Postal service mail sorters, processors, and processing machine operators',
 5600: 'Production, planning, and expediting clerks',
 5610: 'Shipping, receiving, and traffic clerks',
 5620: 'Stock clerks and order fillers',
 5630: 'Weighers, measurers, checkers, and samplers, recordkeeping',
 5700: 'Secretaries and administrative assistants',
 5800: 'Computer operators',
 5810: 'Data entry keyers',
 5820: 'Word processors and typists',
 5830: 'Desktop publishers',
 5840: 'Insurance claims and policy processing clerks',
 5850: 'Mail clerks and mail machine operators, except postal service',
 5860: 'Office clerks, general',
 5900: 'Office machine operators, except computer',
 5910: 'Proofreaders and copy markers',
 5920: 'Statistical assistants',
 5940: 'Office and administrative support workers, all other',
 6005: 'First-line supervisors of farming, fishing, and forestry workers',
 6010: 'Agricultural inspectors',
 6020: 'Animal breeders',
 6040: 'Graders and sorters, agricultural products',
 6050: 'Miscellaneous agricultural workers',
 6100: 'Fishers and related fishing workers',
 6110: 'Hunters and trappers',
 6120: 'Forest and conservation workers',
 6130: 'Logging workers',
 6200: 'First-line supervisors of construction trades and extraction workers',
 6210: 'Boilermakers',
 6220: 'Brickmasons, blockmasons, and stonemasons',
 6230: 'Carpenters',
 6240: 'Carpet, floor, and tile installers and finishers',
 6250: 'Cement masons, concrete finishers, and terrazzo workers',
 6260: 'Construction laborers',
 6300: 'Paving, surfacing, and tamping equipment operators',
 6310: 'Pile-driver operators',
 6320: 'Operating engineers and other construction equipment operators',
 6330: 'Drywall installers, ceiling tile installers, and tapers',
 6355: 'Electricians',
 6360: 'Glaziers',
 6400: 'Insulation workers',
 6420: 'Painters, construction and maintenance',
 6430: 'Paperhangers',
 6440: 'Pipelayers, plumbers, pipefitters, and steamfitters',
 6460: 'Plasterers and stucco masons',
 6500: 'Reinforcing iron and rebar workers',
 6515: 'Roofers',
 6520: 'Sheet metal workers',
 6530: 'Structural iron and steel workers',
 6540: 'Solar photovoltaic installers',
 6600: 'Helpers, construction trades',
 6660: 'Construction and building inspectors',
 6700: 'Elevator installers and repairers',
 6710: 'Fence erectors',
 6720: 'Hazardous materials removal workers',
 6730: 'Highway maintenance workers',
 6740: 'Rail-track laying and maintenance equipment operators',
 6750: 'Septic tank servicers and sewer pipe cleaners',
 6765: 'Miscellaneous construction and related workers',
 6800: 'Derrick, rotary drill, and service unit operators, oil, gas, and mining',
 6820: 'Earth drillers, except oil and gas',
 6830: 'Explosives workers, ordnance handling experts, and blasters',
 6840: 'Mining machine operators',
 6910: 'Roof bolters, mining',
 6920: 'Roustabouts, oil and gas',
 6930: 'Helpers–extraction workers',
 6940: 'Other extraction workers',
 7000: 'First-line supervisors of mechanics, installers, and repairers',
 7010: 'Computer, automated teller, and office machine repairers',
 7020: 'Radio and telecommunications equipment installers and repairers',
 7030: 'Avionics technicians',
 7040: 'Electric motor, power tool, and related repairers',
 7050: 'Electrical and electronics installers and repairers, transportation equipment',
 7100: 'Electrical and electronics repairers, industrial and utility',
 7110: 'Electronic equipment installers and repairers, motor vehicles',
 7120: 'Electronic home entertainment equipment installers and repairers',
 7130: 'Security and fire alarm systems installers',
 7140: 'Aircraft mechanics and service technicians',
 7150: 'Automotive body and related repairers',
 7160: 'Automotive glass installers and repairers',
 7200: 'Automotive service technicians and mechanics',
 7210: 'Bus and truck mechanics and diesel engine specialists',
 7220: 'Heavy vehicle and mobile equipment service technicians and mechanics',
 7240: 'Small engine mechanics',
 7260: 'Miscellaneous vehicle and mobile equipment mechanics, installers, and repairers',
 7300: 'Control and valve installers and repairers',
 7315: 'Heating, air conditioning, and refrigeration mechanics and installers',
 7320: 'Home appliance repairers',
 7330: 'Industrial and refractory machinery mechanics',
 7340: 'Maintenance and repair workers, general',
 7350: 'Maintenance workers, machinery',
 7360: 'Millwrights',
 7410: 'Electrical power-line installers and repairers',
 7420: 'Telecommunications line installers and repairers',
 7430: 'Precision instrument and equipment repairers',
 7440: 'Wind turbine service technicians',
 7510: 'Coin, vending, and amusement machine servicers and repairers',
 7520: 'Commercial divers',
 7540: 'Locksmiths and safe repairers',
 7550: 'Manufactured building and mobile home installers',
 7560: 'Riggers',
 7600: 'Signal and track switch repairers',
 7610: 'Helpers–installation, maintenance, and repair workers',
 7630: 'Other installation, maintenance, and repair workers',
 7700: 'First-line supervisors of production and operating workers',
 7710: 'Aircraft structure, surfaces, rigging, and systems assemblers',
 7720: 'Electrical, electronics, and electromechanical assemblers',
 7730: 'Engine and other machine assemblers',
 7740: 'Structural metal fabricators and fitters',
 7750: 'Miscellaneous assemblers and fabricators',
 7800: 'Bakers',
 7810: 'Butchers and other meat, poultry, and fish processing workers',
 7830: 'Food and tobacco roasting, baking, and drying machine operators and tenders',
 7840: 'Food batchmakers',
 7850: 'Food cooking machine operators and tenders',
 7855: 'Food processing workers, all other',
 7900: 'Computer control programmers and operators',
 7920: 'Extruding and drawing machine setters, operators, and tenders, metal and plastic',
 7930: 'Forging machine setters, operators, and tenders, metal and plastic',
 7940: 'Rolling machine setters, operators, and tenders, metal and plastic',
 7950: 'Cutting, punching, and press machine setters, operators, and tenders, metal and plastic',
 7960: 'Drilling and boring machine tool setters, operators, and tenders, metal and plastic',
 8000: 'Grinding, lapping, polishing, and buffing machine tool setters, operators, and tenders, metal and plastic',
 8010: 'Lathe and turning machine tool setters, operators, and tenders, metal and plastic',
 8020: 'Milling and planing machine setters, operators, and tenders, metal and plastic',
 8030: 'Machinists',
 8040: 'Metal furnace operators, tenders, pourers, and casters',
 8060: 'Model makers and patternmakers, metal and plastic',
 8100: 'Molders and molding machine setters, operators, and tenders, metal and plastic',
 8120: 'Multiple machine tool setters, operators, and tenders, metal and plastic',
 8130: 'Tool and die makers',
 8140: 'Welding, soldering, and brazing workers',
 8150: 'Heat treating equipment setters, operators, and tenders, metal and plastic',
 8160: 'Layout workers, metal and plastic',
 8200: 'Plating and coating machine setters, operators, and tenders, metal and plastic',
 8210: 'Tool grinders, filers, and sharpeners',
 8220: 'Metal workers and plastic workers, all other',
 8250: 'Prepress technicians and workers',
 8255: 'Printing press operators',
 8256: 'Print binding and finishing workers',
 8300: 'Laundry and dry-cleaning workers',
 8310: 'Pressers, textile, garment, and related materials',
 8320: 'Sewing machine operators',
 8330: 'Shoe and leather workers and repairers',
 8340: 'Shoe machine operators and tenders',
 8350: 'Tailors, dressmakers, and sewers',
 8360: 'Textile bleaching and dyeing machine operators and tenders',
 8400: 'Textile cutting machine setters, operators, and tenders',
 8410: 'Textile knitting and weaving machine setters, operators, and tenders',
 8420: 'Textile winding, twisting, and drawing out machine setters, operators, and tenders',
 8430: 'Extruding and forming machine setters, operators, and tenders, synthetic and glass fibers',
 8440: 'Fabric and apparel patternmakers',
 8450: 'Upholsterers',
 8460: 'Textile, apparel, and furnishings workers, all other',
 8500: 'Cabinetmakers and bench carpenters',
 8510: 'Furniture finishers',
 8520: 'Model makers and patternmakers, wood',
 8530: 'Sawing machine setters, operators, and tenders, wood',
 8540: 'Woodworking machine setters, operators, and tenders, except sawing',
 8550: 'Woodworkers, all other',
 8600: 'Power plant operators, distributors, and dispatchers',
 8610: 'Stationary engineers and boiler operators',
 8620: 'Water and wastewater treatment plant and system operators',
 8630: 'Miscellaneous plant and system operators',
 8640: 'Chemical processing machine setters, operators, and tenders',
 8650: 'Crushing, grinding, polishing, mixing, and blending workers',
 8710: 'Cutting workers',
 8720: 'Extruding, forming, pressing, and compacting machine setters, operators, and tenders',
 8730: 'Furnace, kiln, oven, drier, and kettle operators and tenders',
 8740: 'Inspectors, testers, sorters, samplers, and weighers',
 8750: 'Jewelers and precious stone and metal workers',
 8760: 'Medical, dental, and ophthalmic laboratory technicians',
 8800: 'Packaging and filling machine operators and tenders',
 8810: 'Painting workers',
 8830: 'Photographic process workers and processing machine operators',
 8840: 'Semiconductor processors',
 8850: 'Adhesive bonding machine operators and tenders',
 8860: 'Cleaning, washing, and metal pickling equipment operators and tenders',
 8900: 'Cooling and freezing equipment operators and tenders',
 8910: 'Etchers and engravers',
 8920: 'Molders, shapers, and casters, except metal and plastic',
 8930: 'Paper goods machine setters, operators, and tenders',
 8940: 'Tire builders',
 8950: 'Helpers–production workers',
 8965: 'Production workers, all other',
 9000: 'Supervisors of transportation and material moving workers',
 9030: 'Aircraft pilots and flight engineers',
 9040: 'Air traffic controllers and airfield operations specialists',
 9050: 'Flight attendants',
 9110: 'Ambulance drivers and attendants, except emergency medical technicians',
 9120: 'Bus drivers',
 9130: 'Driver/sales workers and truck drivers',
 9140: 'Taxi drivers and chauffeurs',
 9150: 'Motor vehicle operators, all other',
 9200: 'Locomotive engineers and operators',
 9230: 'Railroad brake, signal, and switch operators',
 9240: 'Railroad conductors and yardmasters',
 9260: 'Subway, streetcar, and other rail transportation workers',
 9300: 'Sailors and marine oilers',
 9310: 'Ship and boat captains and operators',
 9330: 'Ship engineers',
 9340: 'Bridge and lock tenders',
 9350: 'Parking lot attendants',
 9360: 'Automotive and watercraft service attendants',
 9410: 'Transportation inspectors',
 9415: 'Transportation attendants, except flight attendants',
 9420: 'Other transportation workers',
 9500: 'Conveyor operators and tenders',
 9510: 'Crane and tower operators',
 9520: 'Dredge, excavating, and loading machine operators',
 9560: 'Hoist and winch operators',
 9600: 'Industrial truck and tractor operators',
 9610: 'Cleaners of vehicles and equipment',
 9620: 'Laborers and freight, stock, and material movers, hand',
 9630: 'Machine feeders and offbearers',
 9640: 'Packers and packagers, hand',
 9650: 'Pumping station operators',
 9720: 'Refuse and recyclable material collectors',
 9730: 'Mine shuttle car operators',
 9740: 'Tank car, truck, and ship loaders',
 9750: 'Material moving workers, all other'},
'IND': {170: 'Crop production',
 180: 'Animal production and aquaculture',
 190: 'Forestry, except logging',
 270: 'Logging',
 280: 'Fishing, hunting, and trapping',
 290: 'Support activities for agriculture and forestry',
 370: 'Oil and gas extraction',
 380: 'Coal mining',
 390: 'Metal ore mining',
 470: 'Nonmetallic mineral mining and quarrying',
 480: 'Not specified type of mining',
 490: 'Support activities for mining',
 770: 'Construction',
 2470: 'Pottery, ceramics, and plumbing fixture manufacturing',
 2480: 'Clay building material and refractories manufacturing',
 2490: 'Glass and glass product manufacturing',
 2570: 'Cement, concrete, lime, and gypsum product manufacturing',
 2590: 'Miscellaneous nonmetallic mineral product manufacturing',
 2670: 'Iron and steel mills and steel product manufacturing',
 2680: 'Aluminum production and processing',
 2690: 'Nonferrous metal, except aluminum, production and processing',
 2770: 'Foundries',
 2780: 'Metal forgings and stampings',
 2790: 'Cutlery and hand tool manufacturing',
 2870: 'Structural metals, and boiler, tank, and shipping container manufacturing',
 2880: 'Machine shops; turned product; screw, nut, and bolt manufacturing',
 2890: 'Coating, engraving, heat treating and allied activities',
 2970: 'Ordnance',
 2980: 'Miscellaneous fabricated metal products manufacturing',
 2990: 'Not specified metal industries',
 3070: 'Agricultural implement manufacturing',
 3080: 'Construction, and mining and oil and gas field machinery manufacturing',
 3095: 'Commercial and service industry machinery manufacturing',
 3170: 'Metalworking machinery manufacturing',
 3180: 'Engine, turbine, and power transmission equipment manufacturing',
 3190: 'Machinery manufacturing, n.e.c.',
 3290: 'Not specified machinery manufacturing',
 3365: 'Computer and peripheral equipment manufacturing',
 3370: 'Communications, and audio and video equipment manufacturing',
 3380: 'Navigational, measuring, electromedical, and control instruments manufacturing',
 3390: 'Electronic component and product manufacturing, n.e.c.',
 3470: 'Household appliance manufacturing',
 3490: 'Electrical lighting and electrical equipment manufacturing, and other electrical component manufacturing, n.e.c.',
 3570: 'Motor vehicles and motor vehicle equipment manufacturing',
 3580: 'Aircraft and parts manufacturing',
 3590: 'Aerospace product and parts manufacturing',
 3670: 'Railroad rolling stock manufacturing',
 3680: 'Ship and boat building',
 3690: 'Other transportation equipment manufacturing',
 3770: 'Sawmills and wood preservation',
 3780: 'Veneer, plywood, and engineered wood products',
 3790: 'Prefabricated wood buildings and mobile homes',
 3875: 'Miscellaneous wood products',
 3895: 'Furniture and related product manufacturing',
 3960: 'Medical equipment and supplies manufacturing',
 3970: 'Sporting and athletic goods, and doll, toy and game manufacturing',
 3980: 'Miscellaneous manufacturing, n.e.c.',
 3990: 'Not specified manufacturing industries',
 1070: 'Animal food, grain, and oilseed milling',
 1080: 'Sugar and confectionery products',
 1090: 'Fruit and vegetable preserving and specialty food manufacturing',
 1170: 'Dairy product manufacturing',
 1180: 'Animal slaughtering and processing',
 1190: 'Retail bakeries',
 1270: 'Bakeries and tortilla manufacturing, except retail bakeries',
 1280: 'Seafood and other miscellaneous foods, n.e.c.',
 1290: 'Not specified food industries',
 1370: 'Beverage manufacturing',
 1390: 'Tobacco manufacturing',
 1470: 'Fiber, yarn, and thread mills',
 1480: 'Fabric mills, except knitting mills',
 1490: 'Textile and fabric finishing and coating mills',
 1570: 'Carpet and rug mills',
 1590: 'Textile product mills, except carpet and rug',
 1670: 'Knitting fabric mills, and apparel knitting mills',
 1680: 'Cut and sew apparel manufacturing',
 1690: 'Apparel accessories and other apparel manufacturing',
 1770: 'Footwear manufacturing',
 1790: 'Leather tanning and finishing and other allied products manufacturing',
 1870: 'Pulp, paper, and paperboard mills',
 1880: 'Paperboard container manufacturing',
 1890: 'Miscellaneous paper and pulp products',
 1990: 'Printing and related support activities',
 2070: 'Petroleum refining',
 2090: 'Miscellaneous petroleum and coal products',
 2170: 'Resin, synthetic rubber and fibers, and filaments manufacturing',
 2180: 'Agricultural chemical manufacturing',
 2190: 'Pharmaceutical and medicine manufacturing',
 2270: 'Paint, coating, and adhesive manufacturing',
 2280: 'Soap, cleaning compound, and cosmetics manufacturing',
 2290: 'Industrial and miscellaneous chemicals',
 2370: 'Plastics product manufacturing',
 2380: 'Tire manufacturing',
 2390: 'Rubber product, except tire, manufacturing',
 4070: 'Motor vehicle and motor vehicle parts and supplies merchant wholesalers',
 4080: 'Furniture and home furnishings merchant wholesalers',
 4090: 'Lumber and other construction materials merchant wholesalers',
 4170: 'Professional and commercial equipment and supplies merchant wholesalers',
 4180: 'Metals and minerals, except petroleum, merchant wholesalers',
 4195: 'Household appliances and electrical and electronic goods merchant wholesalers',
 4265: 'Hardware, and plumbing and heating equipment, and supplies merchant wholesalers',
 4270: 'Machinery, equipment, and supplies merchant wholesalers',
 4280: 'Recyclable material merchant wholesalers',
 4290: 'Miscellaneous durable goods merchant wholesalers',
 4370: 'Paper and paper products merchant wholesalers',
 4380: 'Drugs, sundries, and chemical and allied products merchant wholesalers',
 4390: 'Apparel, piece goods, and notions merchant wholesalers',
 4470: 'Grocery and related product merchant wholesalers',
 4480: 'Farm product raw material merchant wholesalers',
 4490: 'Petroleum and petroleum products merchant wholesalers',
 4560: 'Alcoholic beverages merchant wholesalers',
 4570: 'Farm supplies merchant wholesalers',
 4580: 'Miscellaneous nondurable goods merchant wholesalers',
 4585: 'Wholesale electronic markets and agents and brokers',
 4590: 'Not specified wholesale trade',
 4670: 'Automobile dealers',
 4680: 'Other motor vehicle dealers',
 4690: 'Automotive parts, accessories, and tire stores',
 4770: 'Furniture and home furnishings stores',
 4780: 'Household appliance stores',
 4795: 'Electronics stores',
 4870: 'Building material and supplies dealers',
 4880: 'Hardware stores',
 4890: 'Lawn and garden equipment and supplies stores',
 4970: 'Grocery stores',
 4980: 'Specialty food stores',
 4990: 'Beer, wine, and liquor stores',
 5070: 'Pharmacies and drug stores',
 5080: 'Health and personal care, except drug, stores',
 5090: 'Gasoline stations',
 5170: 'Clothing stores',
 5180: 'Shoe stores',
 5190: 'Jewelry, luggage, and leather goods stores',
 5275: 'Sporting goods, and hobby and toy stores',
 5280: 'Sewing, needlework, and piece goods stores',
 5295: 'Musical instrument and supplies stores',
 5370: 'Book stores and news dealers',
 5380: 'Department stores and discount stores',
 5390: 'Miscellaneous general merchandise stores',
 5470: 'Retail florists',
 5480: 'Office supplies and stationery stores',
 5490: 'Used merchandise stores',
 5570: 'Gift, novelty, and souvenir shops',
 5580: 'Miscellaneous retail stores',
 5590: 'Electronic shopping',
 5591: 'Electronic auctions',
 5592: 'Mail-order houses',
 5670: 'Vending machine operators',
 5680: 'Fuel dealers',
 5690: 'Other direct selling establishments',
 5790: 'Not specified retail trade',
 6070: 'Air transportation',
 6080: 'Rail transportation',
 6090: 'Water transportation',
 6170: 'Truck transportation',
 6180: 'Bus service and urban transit',
 6190: 'Taxi and limousine service',
 6270: 'Pipeline transportation',
 6280: 'Scenic and sightseeing transportation',
 6290: 'Services incidental to transportation',
 6370: 'Postal Service',
 6380: 'Couriers and messengers',
 6390: 'Warehousing and storage',
 570: 'Electric power generation, transmission, and distribution',
 580: 'Natural gas distribution',
 590: 'Electric and gas, and other combinations',
 670: 'Water, steam, air-conditioning, and irrigation systems',
 680: 'Sewage treatment facilities',
 690: 'Not specified utilities',
 6470: 'Newspaper publishers',
 6480: 'Periodical, book, and directory publishers',
 6490: 'Software publishers',
 6570: 'Motion pictures and video industries',
 6590: 'Sound recording industries',
 6670: 'Radio and television broadcasting and cable subscription programming',
 6672: 'Internet publishing and broadcasting and web search portals',
 6680: 'Wired telecommunications carriers',
 6690: 'Other telecommunications services',
 6695: 'Data processing, hosting, and related services',
 6770: 'Libraries and archives',
 6780: 'Other information services',
 6870: 'Banking and related activities',
 6880: 'Savings institutions, including credit unions',
 6890: 'Nondepository credit and related activities',
 6970: 'Securities, commodities, funds, trusts, and other financial investments',
 6990: 'Insurance carriers and related activities',
 7070: 'Real estate',
 7080: 'Automotive equipment rental and leasing',
 7170: 'Videotape and disk rental',
 7180: 'Other consumer goods rental',
 7190: 'Commercial, industrial, and other intangible assets rental and leasing',
 7270: 'Legal services',
 7280: 'Accounting, tax preparation, bookkeeping, and payroll services',
 7290: 'Architectural, engineering, and related services',
 7370: 'Specialized design services',
 7380: 'Computer systems design and related services',
 7390: 'Management, scientific, and technical consulting services',
 7460: 'Scientific research and development services',
 7470: 'Advertising, public relations, and related services',
 7480: 'Veterinary services',
 7490: 'Other professional, scientific, and technical services',
 7570: 'Management of companies and enterprises',
 7580: 'Employment services',
 7590: 'Business support services',
 7670: 'Travel arrangements and reservation services',
 7680: 'Investigation and security services',
 7690: 'Services to buildings and dwellings',
 7770: 'Landscaping services',
 7780: 'Other administrative and other support services',
 7790: 'Waste management and remediation services',
 7860: 'Elementary and secondary schools',
 7870: 'Colleges, universities, and professional schools, including junior colleges',
 7880: 'Business, technical, and trade schools and training',
 7890: 'Other schools and instruction, and educational support services',
 8190: 'Hospitals',
 7970: 'Offices of physicians',
 7980: 'Offices of dentists',
 7990: 'Offices of chiropractors',
 8070: 'Offices of optometrists',
 8080: 'Offices of other health practitioners',
 8090: 'Outpatient care centers',
 8170: 'Home health care services',
 8180: 'Other health care services',
 8270: 'Nursing care facilities (skilled nursing facilities)',
 8290: 'Residential care facilities, except skilled nursing facilities',
 8370: 'Individual and family services',
 8380: 'Community food and housing, and emergency services',
 8390: 'Vocational rehabilitation services',
 8470: 'Child day care services',
 8560: 'Independent artists, performing arts, spectator sports, and related industries',
 8570: 'Museums, art galleries, historical sites, and similar institutions',
 8580: 'Bowling centers',
 8590: 'Other amusement, gambling, and recreation industries',
 8660: 'Traveler accommodation',
 8670: 'Recreational vehicle parks and camps, and rooming and boarding houses',
 8680: 'Restaurants and other food services',
 8690: 'Drinking places, alcoholic beverages',
 8770: 'Automotive repair and maintenance',
 8780: 'Car washes',
 8790: 'Electronic and precision equipment repair and maintenance',
 8870: 'Commercial and industrial machinery and equipment repair and maintenance',
 8880: 'Personal and household goods repair and maintenance',
 8890: 'Footwear and leather goods repair',
 8970: 'Barber shops',
 8980: 'Beauty salons',
 8990: 'Nail salons and other personal care services',
 9070: 'Drycleaning and laundry services',
 9080: 'Funeral homes, and cemeteries and crematories',
 9090: 'Other personal services',
 9160: 'Religious organizations',
 9170: 'Civic, social, advocacy organizations, and grantmaking and giving services',
 9180: 'Labor unions',
 9190: 'Business, professional, political, and similar organizations',
 9290: 'Private households',
 9370: 'Executive offices and legislative bodies',
 9380: 'Public finance activities',
 9390: 'Other general government and support',
 9470: 'Justice, public order, and safety activities',
 9480: 'Administration of human resource programs',
 9490: 'Administration of environmental quality and housing programs',
 9570: 'Administration of economic programs and space research',
 9590: 'National security and international affairs'},
'INDD':{1: 'Agriculture',
 2: 'Forestry, logging, fishing, hunting, and trapping',
 3: 'Mining',
 4: 'Construction',
 5: 'Nonmetallic mineral product manufacturing',
 6: 'Primary metals and fabricated metal products',
 7: 'Machinery  manufacturing',
 8: 'Computer and electronic product manufacturing',
 9: 'Electrical equipment, appliance manufacturing',
 10: 'Transportation equipment manufacturing',
 11: 'Wood products',
 12: 'Furniture and fixtures manufacturing',
 13: 'Miscellaneous and not specified manufacturing',
 14: 'Food manufacturing',
 15: 'Beverage and tobacco products',
 16: 'Textile, apparel, and leather manufacturing',
 17: 'Paper and printing',
 18: 'Petroleum and coal products manufacturing',
 19: 'Chemical manufacturing',
 20: 'Plastics and rubber products',
 21: 'Wholesale trade',
 22: 'Retail trade',
 23: 'Transportation and warehousing',
 24: 'Utilities',
 25: 'Publishing industries (except internet)',
 26: 'Motion picture and sound recording industries',
 27: 'Broadcasting (except internet)',
 28: 'Internet publishing and broadcasting',
 29: 'Telecommunications',
 30: 'Internet service providers and data processing services',
 31: 'Other information services',
 32: 'Finance',
 33: 'Insurance',
 34: 'Real estate',
 35: 'Rental and leasing services',
 36: 'Professional and  technical services',
 37: 'Management of companies and enterprises',
 38: 'Administrative and support services',
 39: 'Waste management and remediation services',
 40: 'Educational services',
 41: 'Hospitals',
 42: 'Health care services, except hospitals',
 43: 'Social assistance',
 44: 'Arts, entertainment, and recreation',
 45: 'Accommodation',
 46: 'Food services and drinking places',
 47: 'Repair and maintenance',
 48: 'Personal and laundry services',
 49: 'Membership associations and organizations',
 50: 'Private households',
 51: 'Public administration',
 52: 'Armed forces'},
'OCCD': {1: 'Management occupations',
 2: 'Business and financial operations occupations',
 3: 'Computer and mathematical science occupations',
 4: 'Architecture and engineering occupations',
 5: 'Life, physical, and social science occupations',
 6: 'Community and social service occupations',
 7: 'Legal occupations',
 8: 'Education, training, and library occupations',
 9: 'Arts, design, entertainment, sports, and media',
 10: 'Healthcare practitioner and technical occupations',
 11: 'Healthcare support occupations',
 12: 'Protective service occupations',
 13: 'Food preparation and serving related occupations',
 14: 'Building and grounds cleaning and maintenance',
 15: 'Personal care and service occupations',
 16: 'Sales and related occupations',
 17: 'Office and administrative support occupations',
 18: 'Farming, fishing, and forestry occupations',
 19: 'Construction and extraction occupations',
 20: 'Installation, maintenance, and repair occupations',
 21: 'Production occupations',
 22: 'Transportation and material moving occupations',
 23: 'Armed Forces'},
'INDM': {1: 'Agriculture, forestry, fishing, and hunting',
 2: 'Mining',
 3: 'Construction',
 4: 'Manufacturing',
 5: 'Wholesale and retail trade',
 6: 'Transportation and utilities',
 7: 'Information',
 8: 'Financial activities',
 9: 'Professional and business services',
 10: 'Educational and health services',
 11: 'Leisure and hospitality',
 12: 'Other services',
 13: 'Public administration'},
'OCCM': {1: 'Management, business, and financial occupations',
 2: 'Professional and related occupations',
 3: 'Service occupations',
 4: 'Sales and related occupations',
 5: 'Office and administrative support occupations',
 6: 'Farming, fishing, and forestry occupations',
 7: 'Construction and extraction occupations',
 8: 'Installation, maintenance, and repair occupations',
 9: 'Production occupations',
 10: 'Transportation and material moving occupations',
 11: 'Armed Forces'}}